apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battlecats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: battlecats
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gateszhangc/battlecats.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
