---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: battlecats
spec:
  encryptedData:
    api-token: AgA6QWgZx3cQ78ulnUQT6/XoP7KIujXatSPd8Zj5A7mq3w84D/1GSA4USfRsATgQE01+TKucByJPB/Cok5d88YmiE6rG1JfyCKsJUZj2ttdLdaB3BmZMYnp/z7zV84y3ss8Bct0HU2OVDH3WkknLh7zLqnBYUY1hR/vcCYpZ/9kah/V+3YFy55Ud+8HaDyfCy9lMtRx5LrO/fcsbz95uqKARTd2xjUdUKrCUumgXbPR2qukpYi+yVqIpeu3/jRPLCsbEMwlrskl+WmNYZ0p67N7Yk4Y7t+IR8UaGDfNFwe+RRkGfv7Rer2Rqd+N138+VN4xhFNYHeKiYgqGEWuRM3w3pngF6yRjV0MyXWVJIwngL900ZAqedfDhw+YX+Bk/Wz2ucWID/5Ffy9xPedqGG8pk28yNlstRH2xR1LLK8aqgHhLuWMufMTWmbrPstERfLzlT6rZ143H5GLUIB2pVhGEs8mZsdOhQvpJM8OTT47njNVlyUQXS2y56NdSxXcMzVZHgaefo1OIaPiY8vHX4u8fxB0xmKoDb/CvTFNxR/1YuZUf5pQV5Y4y4RPloZ/OEgJ38Xc3r3Bf8x0r77O0In0XpiYDhCytIWKR41rRvCbLNhrU20ZGRbczwTGHUBpte8qVYXSSalbDaDy9NbMxHAuy+ukT0z4+ymtWR8Zv423wsS0QbDxIElRPQZXEvvPPX6mKMEesMCD6eUChBATt/+8Fo8Pagwlgzz2NJi4CNbeziRHISqjp9shLRL
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: battlecats
