apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: battlecats-live-redirect
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://battlecats.lol$request_uri
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: www.battlecats.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: battlecats
                port:
                  number: 80
  tls:
    - hosts:
        - www.battlecats.lol
      secretName: battlecats-live-tls
