apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: battlecats

resources:
  - ../../base
  - cloudflare-api-token.sealedsecret.yaml
  - registry-credentials.sealedsecret.yaml
  - issuer-cloudflare.yaml
  - ingress-live.yaml
  - ingress-www-redirect.yaml
  - ingress-preview.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true

images:
  - name: battlecats
    newName: registry.144.91.77.245.sslip.io/battlecats
    newTag: bootstrap
