---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: battlecats-registry
  namespace: battlecats
spec:
  encryptedData:
    .dockerconfigjson: AgCFZFdj8gA8LcEJwukSDDt8Hch1xBbBDi+qZ+e1laGTZkflfFj9l5cteNVbaEL/5Ljd6BsiN9Q9A9eYrn2e+1hXaSguSjU8l1LBPjTsKzrs/lk7wtKh1SKF+CpH9CBKwRbLZsbJRuf59kG3Jlv7G2LQ+6JodoHJW6V3+/sGhnAoSYGvFf64u4s+XTlVTDsNupB1VMZcc6+1WU2aiXsITuzYGJUhcwm2ZU0eay+mHlXjh2BYqz/oNRG6pJzTEDGeSztEVcR+3KX15d81KEHZAoET6VDBmmNRLf+ze2tJEdIcq91Is4KfbJy6n2rzFhyd9ob0+P1eVtDVDHU04SqOTgWeht0PSyhuul1F4jl/RkzbAb5oLDBli/51BXuLZM687ub0tOEudyGEitsPnxj22y5wuIGmFOAGw8VsTqFuxE2Bk8MdufCwy6B5ItZBg+aI7ro71nSBt078XcPC0TbQTQDRd7EfesA50cpXnZFEzw/ZzDsmW2/RcHMr/Nm+cGT0EV/aQlTQKAiA2Bz7xVEQS6KUynS0WfrrOT/p/bxBiQK/DOw2EwJpU7wGUE8oi0v+4K0dXGjwG7bTHDAH9ybI4Dho6mK+tkxKJk+jtpOlIwrI37Lr+GCCxxFZT5R/LyeSG7dFyJsUR66JTIoftzt514Lg5k41oAY3GsSBzP3QeFq8xx+VBS7/+Nv1b6NKUb3d4XTzuJwB6qEzkZ43DSm3FxYSkVJ6IbOCw1zK0lXe6kNGDTG85YTzsZr422aKeJGvqI/Vt0dy+hk0smB6AGqmHNO6Kse6E+z1eTFtClAxYGfUVXZubi4CR9sfepQHObIlt0U6Ql/sv/DlKmZcp+XfhkAVsarAyiTTbvKaZWBwysd1Q/QogcSGEC2bdWZLFSCXlZ6oTzkWLm3xckVkbPoOZEH50Rswj3z8KJOe0tW/BOnxEQf8UOvUMEX8fhxvh2TivOSDHm86yvTP+SlC1CF9NLiQ
  template:
    metadata:
      name: battlecats-registry
      namespace: battlecats
    type: kubernetes.io/dockerconfigjson
